# Generated by Django 4.2.20 on 2025-03-23 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Service"),
                            ("calendar", "Calendar Service"),
                            ("storage", "Storage Service"),
                            ("payment", "Payment Gateway"),
                            ("social", "Social Media"),
                            ("chat", "Chat Service"),
                            ("erp", "ERP System"),
                            ("custom", "Custom Integration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("pending", "Pending Configuration"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("configuration", models.JSONField(default=dict)),
                ("credentials", models.JSONField(default=dict)),
                ("webhook_url", models.URLField(blank=True)),
                ("api_key", models.CharField(blank=True, max_length=500)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("contact_created", "Contact Created"),
                            ("contact_updated", "Contact Updated"),
                            ("deal_created", "Deal Created"),
                            ("deal_updated", "Deal Updated"),
                            ("ticket_created", "Ticket Created"),
                            ("ticket_updated", "Ticket Updated"),
                            ("custom", "Custom Event"),
                        ],
                        max_length=50,
                    ),
                ),
                ("url", models.URLField()),
                ("secret_key", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="integrations.integration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("partial", "Partial Success"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("records_processed", models.PositiveIntegerField(default=0)),
                ("records_succeeded", models.PositiveIntegerField(default=0)),
                ("records_failed", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("details", models.JSONField(default=dict)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="integrations.integration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_model", models.CharField(max_length=100)),
                ("target_model", models.CharField(max_length=100)),
                (
                    "mapping_type",
                    models.CharField(
                        choices=[
                            ("field", "Field Mapping"),
                            ("value", "Value Mapping"),
                            ("function", "Function Mapping"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_field", models.CharField(max_length=100)),
                ("target_field", models.CharField(max_length=100)),
                ("transformation_rule", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_mappings",
                        to="integrations.integration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("external_id", models.CharField(max_length=255)),
                ("external_url", models.URLField(blank=True)),
                ("last_synced", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["integration", "content_type", "object_id"],
                        name="integration_integra_eda47d_idx",
                    ),
                    models.Index(
                        fields=["external_id"], name="integration_externa_6ac5d6_idx"
                    ),
                ],
                "unique_together": {
                    ("integration", "content_type", "object_id", "external_id")
                },
            },
        ),
    ]
